# Generated by Django 5.2.14 on 2026-06-01 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("splits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="splitpayment",
            name="status",
        ),
    ]
