# Generated by Django 5.2.14 on 2026-06-02 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
        ("transactions", "0003_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashinvoice",
            name="type",
            field=models.CharField(
                choices=[("REQUEST", "Request"), ("EXPENSE", "Expense")],
                default="REQUEST",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cashinvoice",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.transaction",
            ),
        ),
    ]
