# Generated by Django 5.2.14 on 2026-06-02 05:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_cashinvoice_type_alter_cashinvoice_transaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cashinvoice",
            old_name="type",
            new_name="invoice_type",
        ),
    ]
