# Generated by Django 5.2.14 on 2026-06-03 05:13

import apps.invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_rename_type_cashinvoice_invoice_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashinvoice",
            name="expires_at",
            field=models.DateTimeField(
                default=apps.invoices.models.default_expiry_time
            ),
        ),
        migrations.AddField(
            model_name="cashinvoice",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
