# Generated by Django 5.2.14 on 2026-06-26 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_cashinvoice_expires_at_cashinvoice_reminder_sent"),
        ("wallets", "0003_wallet_created_by_wallet_group_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashinvoice",
            name="target_wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_requests",
                to="wallets.wallet",
            ),
        ),
    ]
