# Generated by Django 5.2.14 on 2026-05-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("TRANSFER", "Transfer"),
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAWAL", "Withdrawal"),
                ],
                default="TRANSFER",
                max_length=20,
            ),
        ),
    ]
