# Generated by Django 5.2.14 on 2026-06-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_transaction_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("TRANSFER", "Transfer"),
                    ("DEPOSIT", "Deposit"),
                    ("GROUP_CONTRIBUTION", "Group Contribution"),
                    ("GROUP_EXPENSE", "Group Expense"),
                    ("WITHDRAWAL", "Withdrawal"),
                ],
                default="TRANSFER",
                max_length=20,
            ),
        ),
    ]
