# Generated by Django 5.2.14 on 2026-06-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0003_wallet_created_by_wallet_group_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="spending_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
